[chainIDMap]
"OPT" = "18"
"AVAX" = "19"
"POLY" = "20"
"ETH" = "21"
"BSC" = "22"
"ARB" = "23"
"BASE" = "24"
"WEMIX" = "27"
"KROMA" = "28"
"GNO" = "30"

[chainMappings]
"ethereum-mainnet-arbitrum-1" = "Arbitrum Mainnet"
"ethereum-mainnet-base-1" = "Base Mainnet"
"ethereum-mainnet-optimism-1" = "Optimism Mainnet"
"matic-mainnet" = "Polygon Mainnet"
"ethereum-mainnet" = "Ethereum Mainnet"
"avalanche-mainnet" = "Avalanche Mainnet"
"bsc-mainnet" = "BSC Mainnet"
"ethereum-mainnet-kroma-1" = "Kroma Mainnet"
"wemix-mainnet" = "WeMix Mainnet"
"xdai-mainnet" = "GnosisChain Mainnet"

[laneIDMap]
"ARB,BASE" = "37"
"ETH,OPT" = "38"
"AVAX,ETH" = "39"
"ETH,POLY" = "40"
"AVAX,POLY" = "41"
"BSC,ETH" = "42"
"ARB,ETH" = "43"
"BASE,ETH" = "44"
"BASE,OPT" = "46"
"AVAX,BSC" = "47"
"BSC,POLY" = "48"
"OPT,POLY" = "49"
"BASE,BSC" = "50"
"ETH,WEMIX" = "51"
"KROMA,WEMIX" = "52"
"ARB,POLY" = "53"
"ARB,BSC" = "54"
"ARB,OPT" = "55"
"ARB,AVAX" = "56"
"AVAX,OPT" = "57"
"BASE,POLY" = "58"
"BSC,OPT" = "59"
"AVAX,BASE" = "60"
"BSC,WEMIX" = "61"
"AVAX,WEMIX" = "62"
"POLY,WEMIX" = "63"
"ARB,WEMIX" = "64"
"OPT,WEMIX" = "65"
"ETH,GNO" = "68"
"GNO,POLY" = "69"