[shortcutMappings]
"KROMA" = "Kroma Mainnet"
"WEMIX" = "WeMix Mainnet"
"GNO" = "GnosisChain Mainnet"
"OPT" = "Optimism Mainnet"
"AVAX" = "Avalanche Mainnet"
"POLY" = "Polygon Mainnet"
"BSC" = "BSC Mainnet"
"ETH" = "Ethereum Mainnet"
"ARB" = "Arbitrum Mainnet"
"BASE" = "Base Mainnet"

[chainIDMap]
"Optimism Mainnet" = "18"
"Avalanche Mainnet" = "19"
"Polygon Mainnet" = "20"
"Ethereum Mainnet" = "21"
"BSC Mainnet" = "22"
"Arbitrum Mainnet" = "23"
"Base Mainnet" = "24"
"WeMix Mainnet" = "27"
"Kroma Mainnet" = "28"
"GnosisChain Mainnet" = "30"

[chainMappings]
"ethereum-mainnet-arbitrum-1" = "Arbitrum Mainnet"
"ethereum-mainnet-base-1" = "Base Mainnet"
"ethereum-mainnet-optimism-1" = "Optimism Mainnet"
"matic-mainnet" = "Polygon Mainnet"
"ethereum-mainnet" = "Ethereum Mainnet"
"avalanche-mainnet" = "Avalanche Mainnet"
"bsc-mainnet" = "BSC Mainnet"
"ethereum-mainnet-kroma-1" = "Kroma Mainnet"
"wemix-mainnet" = "WeMix Mainnet"
"xdai-mainnet" = "GnosisChain Mainnet"

[nativeFeeTokenMap]
"Optimism Mainnet" = "0x4200000000000000000000000000000000000006"
"Avalanche Mainnet" = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
"Polygon Mainnet" = "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
"Ethereum Mainnet" = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
"BSC Mainnet" = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
"Arbitrum Mainnet" = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
"Base Mainnet" = "0x4200000000000000000000000000000000000006"
"WeMix Mainnet" = "0x7D72b22a74A216Af4a002a1095C8C707d6eC1C5f"
"Kroma Mainnet" = "0x4200000000000000000000000000000000000001"
"GnosisChain Mainnet" = "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"


[laneIDMap]
"Arbitrum Mainnet,Base Mainnet" = "37"
"Ethereum Mainnet,Optimism Mainnet" = "38"
"Avalanche Mainnet,Ethereum Mainnet" = "39"
"Ethereum Mainnet,Polygon Mainnet" = "40"
"Avalanche Mainnet,Polygon Mainnet" = "41"
"BSC Mainnet,Ethereum Mainnet" = "42"
"Arbitrum Mainnet,Ethereum Mainnet" = "43"
"Base Mainnet,Ethereum Mainnet" = "44"
"Base Mainnet,Optimism Mainnet" = "46"
"Avalanche Mainnet,BSC Mainnet" = "47"
"BSC Mainnet,Polygon Mainnet" = "48"
"Optimism Mainnet,Polygon Mainnet" = "49"
"Base Mainnet,BSC Mainnet" = "50"
"Ethereum Mainnet,WeMix Mainnet" = "51"
"Kroma Mainnet,WeMix Mainnet" = "52"
"Arbitrum Mainnet,Polygon Mainnet" = "53"
"Arbitrum Mainnet,BSC Mainnet" = "54"
"Arbitrum Mainnet,Optimism Mainnet" = "55"
"Arbitrum Mainnet,Avalanche Mainnet" = "56"
"Avalanche Mainnet,Optimism Mainnet" = "57"
"Base Mainnet,Polygon Mainnet" = "58"
"BSC Mainnet,Optimism Mainnet" = "59"
"Avalanche Mainnet,Base Mainnet" = "60"
"BSC Mainnet,WeMix Mainnet" = "61"
"Avalanche Mainnet,WeMix Mainnet" = "62"
"Polygon Mainnet,WeMix Mainnet" = "63"
"Arbitrum Mainnet,WeMix Mainnet" = "64"
"Optimism Mainnet,WeMix Mainnet" = "65"
"Ethereum Mainnet,GnosisChain Mainnet" = "68"
"GnosisChain Mainnet,Polygon Mainnet" = "69"