LanePairs = [
    "Ethereum-Optimism",
    "Ethereum-Avalanche",
    "Ethereum-Polygon",
    "Ethereum-BSC",
    "Ethereum-Arbitrum",
    "Ethereum-Base",
    # "Avalanche-Polygon",
    "Base-Optimism",
    "Base-Arbitrum",
    # "Avalanche-BSC",
    # "BSC-Polygon",
    "Optimism-Polygon",
    # "Base-BSC",
    "Polygon-Arbitrum",
    "Arbitrum-BSC",
    "Arbitrum-Optimism",
    "Avalanche-Optimism",
    "Avalanche-Arbitrum",
    # "Base-Polygon",
    "BSC-Optimism",
    # "Avalanche-Base",
    "Avalanche-Wemix",
    "Arbitrum-Wemix",
    "BSC-Wemix",
    "Ethereum-Wemix",
    "Kroma-Wemix",
    "Optimism-Wemix",
    "Polygon-Wemix"
]
